"""
Electric Money V14 - consolidated multi-node testnet/reference implementation

Evolution consolidated from CA Blockchain v2 through Electric Money V13/V14, preserving
the cumulative consensus/network functionality developed across the versions.

This is still NOT production/mainnet cryptocurrency software.

Key V14 economic changes:
- 10-minute target block time, aligned with Bitcoin
- cumulative proof-of-work is used for chain selection, not chain length
- hard cap is based on TOTAL ISSUED
- every incoming L1 payment is charged 0.25% total: 0.20% to Treasury + 0.05% burned
- every wallet has a deterministic on-chain tax anchor; every 365 days its full current balance is charged 0.25%: 0.20% to Treasury + 0.05% burned
- ordinary transfers therefore carry a 0.05% burn, while the incoming-balance levy funds Treasury and burn
- no wallet activation fee
- Treasury is emptied monthly and distributed to miners according to verified PoW work in that month
- share jobs are tied to canonical parent tips
- full chain replay is the source of truth for state
- transaction timestamps, addresses, signatures and nonces are checked
- block size / transaction count limits
- median-time-past and future-time checks
- mempool de-duplication and nonce handling
- orphan/fork block storage and heavier-chain adoption
- peer handshake, TX/BLOCK propagation and chain synchronization
- configurable peers and node identity
- deterministic L2 batch commitments are included in L1 blocks
- L2 is explicitly a sequencer/commitment layer, not a trustless rollup
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import secrets
import socket
import struct
import threading
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from ecdsa import SigningKey, VerifyingKey, SECP256k1, BadSignatureError


# ============================================================
# CONSENSUS CONFIG
# ============================================================

COIN = 100_000_000
MAX_SUPPLY = 7_227_002_484_100_600      # 72,270,024.841006 EM exact cap for 27.5-year halvings
BASE_REWARD = 25 * COIN
# Bitcoin-style subsidy halving.
# V13 uses 1,445,400 blocks per halving = exactly 27.5 years at
# the 600-second target block time, with 8 decimal places.
# MAX_SUPPLY is the exact integer-denomination total generated by this schedule.
INITIAL_BLOCK_REWARD = 25 * COIN          # 25 EM
HALVING_INTERVAL = 1_445_400       # exactly 27.5 years at 600 s/block (365-day years)

TX_BURN_BPS = 5                         # 0.05% burned from every transfer
RECEIVER_TAX_BPS = 20                   # 0.20% Treasury tax on every incoming payment; 0.05% burn makes 0.25% total
TARGET_BLOCK_TIME = 600
MONTH_SECONDS = 30 * 24 * 60 * 60
YEAR_SECONDS = 365 * 24 * 60 * 60
MINER_REWARD_EPOCH_BLOCKS = MONTH_SECONDS // TARGET_BLOCK_TIME  # 30 days at 10-minute target blocks
DIFFICULTY_INTERVAL = 10
GENESIS_DIFFICULTY = 2
MIN_DIFFICULTY = 1
MAX_DIFFICULTY = 32

MAX_FUTURE_BLOCK_TIME = 120
MAX_TX_AGE = 24 * 60 * 60
MAX_TX_AMOUNT = MAX_SUPPLY
MAX_TX_PER_BLOCK = 5000
MAX_BLOCK_BYTES = 2 * 1024 * 1024
MTP_WINDOW = 11

NETWORK_ID = "ELECTRIC-MONEY-TESTNET-V14"
PROTOCOL_VERSION = 14
MAX_FRAME_BYTES = 16 * 1024 * 1024
MAX_ORPHANS = 2048
MAX_PEERS = 64

# PoW shares are verifiable work proofs tied to a canonical parent block.
# Share difficulty is derived from the parent block difficulty; no self-reported hashrate is trusted.
MINING_SHARE_MIN_DIFFICULTY = 1
SHARE_DIFFICULTY_OFFSET = 1       # shares are 16x easier than the parent block
MAX_SHARES_PER_BLOCK = 256
MAX_PENDING_SHARES = 20_000

GENESIS_MESSAGE = (
    "ELECTRIC MONEY - Genesis Block. "
    "Utility protocol with 0.25% incoming payment levy (0.20% Treasury + 0.05% burn), "
    "0.25% annual wallet balance levy (0.20% Treasury + 0.05% burn), "
    "and 72,270,024.841006 EM maximum cumulative issuance."
)

ZERO_HASH = "0" * 128
L2_BRIDGE_ADDRESS = "EM_L2_BRIDGE"
TREASURY_ADDRESS = "ELECTRIC_MONEY_TREASURY"


# ============================================================
# HASH / SERIALIZATION
# ============================================================

def sha3_512_hex(data: bytes) -> str:
    return hashlib.sha3_512(data).hexdigest()


def canonical_json(obj: Any) -> bytes:
    return json.dumps(
        obj,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
    ).encode("utf-8")


def hash_obj(obj: Any) -> str:
    return sha3_512_hex(canonical_json(obj))


def checked_amount(value: int) -> int:
    if not isinstance(value, int) or isinstance(value, bool):
        raise ValueError("amount must be an integer base-unit value")
    if value <= 0 or value > MAX_TX_AMOUNT:
        raise ValueError("amount outside allowed range")
    return value


def is_hex(value: str, length: Optional[int] = None) -> bool:
    if not isinstance(value, str):
        return False
    if length is not None and len(value) != length:
        return False
    try:
        bytes.fromhex(value)
        return True
    except (ValueError, TypeError):
        return False


# ============================================================
# MERKLE TREE
# ============================================================

class MerkleTree:
    @staticmethod
    def compute_root(items: List[str]) -> str:
        if not items:
            return sha3_512_hex(b"")
        level = [str(x) for x in items]
        while len(level) > 1:
            if len(level) % 2:
                level.append(level[-1])
            level = [
                sha3_512_hex((level[i] + level[i + 1]).encode("ascii"))
                for i in range(0, len(level), 2)
            ]
        return level[0]


# ============================================================
# WALLET
# ============================================================

class Wallet:
    def __init__(self, private_key: Optional[bytes] = None):
        self._private_key = (
            SigningKey.from_string(private_key, curve=SECP256k1)
            if private_key else SigningKey.generate(curve=SECP256k1)
        )
        self.public_key_hex = self._private_key.verifying_key.to_string().hex()
        self.address = sha3_512_hex(bytes.fromhex(self.public_key_hex))

    def sign(self, message: bytes) -> str:
        return self._private_key.sign_deterministic(
            message, hashfunc=hashlib.sha3_512
        ).hex()

    def sign_transaction(self, tx: "Transaction") -> "Transaction":
        tx.signature = self.sign(tx.signing_bytes())
        tx.tx_id = tx.calculate_id()
        return tx

    @staticmethod
    def verify(pubkey_hex: str, message: bytes, signature_hex: str) -> bool:
        try:
            vk = VerifyingKey.from_string(
                bytes.fromhex(pubkey_hex), curve=SECP256k1
            )
            return vk.verify(
                bytes.fromhex(signature_hex),
                message,
                hashfunc=hashlib.sha3_512,
            )
        except (BadSignatureError, ValueError, TypeError):
            return False

    @staticmethod
    def address_from_pubkey(pubkey_hex: str) -> str:
        if not is_hex(pubkey_hex, 128):
            raise ValueError("invalid public key")
        return sha3_512_hex(bytes.fromhex(pubkey_hex))


# ============================================================
# L1 TRANSACTION
# ============================================================

@dataclass
class Transaction:
    sender_pubkey: str
    recipient: str
    amount: int
    nonce: int
    timestamp: int
    signature: str = ""
    tx_id: str = ""

    def sender_address(self) -> str:
        return Wallet.address_from_pubkey(self.sender_pubkey)

    def burned(self) -> int:
        return (self.amount * TX_BURN_BPS) // 10_000

    def receiver_tax(self) -> int:
        # Treasury portion of the incoming-payment levy.
        return (self.amount * RECEIVER_TAX_BPS) // 10_000

    def net_amount(self) -> int:
        # Sender pays the full amount; Treasury gets 0.20% and 0.05% is burned.
        return self.amount - self.receiver_tax() - self.burned()

    def signing_dict(self) -> Dict[str, Any]:
        return {
            "sender_pubkey": self.sender_pubkey,
            "recipient": self.recipient,
            "amount": self.amount,
            "nonce": self.nonce,
            "timestamp": self.timestamp,
        }

    def signing_bytes(self) -> bytes:
        return canonical_json(self.signing_dict())

    def calculate_id(self) -> str:
        return hash_obj({
            **self.signing_dict(),
            "signature": self.signature,
        })

    def is_valid(self, now: Optional[int] = None) -> bool:
        try:
            now = int(time.time()) if now is None else now
            checked_amount(self.amount)

            if self.nonce < 0:
                return False
            if not is_hex(self.sender_pubkey, 128):
                return False
            if not isinstance(self.recipient, str) or len(self.recipient) != 128:
                return False
            if not is_hex(self.recipient, 128):
                return False
            if self.recipient == "SYSTEM":
                return False
            if self.timestamp < now - MAX_TX_AGE:
                return False
            if self.timestamp > now + MAX_FUTURE_BLOCK_TIME:
                return False
            if not self.signature or not is_hex(self.signature):
                return False

            expected_id = self.calculate_id()
            if self.tx_id != expected_id:
                return False

            return Wallet.verify(
                self.sender_pubkey,
                self.signing_bytes(),
                self.signature,
            )
        except (ValueError, TypeError):
            return False

    def to_dict(self) -> Dict[str, Any]:
        return {
            **self.signing_dict(),
            "signature": self.signature,
            "tx_id": self.tx_id or self.calculate_id(),
        }

    @staticmethod
    def from_dict(d: Dict[str, Any]) -> "Transaction":
        return Transaction(
            sender_pubkey=d["sender_pubkey"],
            recipient=d["recipient"],
            amount=int(d["amount"]),
            nonce=int(d["nonce"]),
            timestamp=int(d["timestamp"]),
            signature=d.get("signature", ""),
            tx_id=d.get("tx_id", ""),
        )


# ============================================================
# VERIFIED POW SHARES
# ============================================================

@dataclass
class MiningShare:
    miner: str
    job_id: str
    difficulty: int
    nonce: int
    share_hash: str = ""
    share_id: str = ""

    @staticmethod
    def challenge(job_id: str, difficulty: int) -> str:
        return sha3_512_hex(
            f"ELECTRIC-MONEY-SHARE-{NETWORK_ID}-{job_id}-{difficulty}".encode("ascii")
        )

    def calculate_hash(self) -> str:
        payload = (self.challenge(self.job_id, self.difficulty) + self.miner + str(self.nonce)).encode("ascii")
        return sha3_512_hex(payload)

    def calculate_id(self) -> str:
        return hash_obj({
            "type": "mining_share",
            "miner": self.miner,
            "job_id": self.job_id,
            "difficulty": self.difficulty,
            "nonce": self.nonce,
            "share_hash": self.share_hash,
        })

    def is_valid(self, expected_job_id: Optional[str] = None, expected_difficulty: Optional[int] = None) -> bool:
        if not is_hex(self.miner, 128):
            return False
        if not is_hex(self.job_id, 128):
            return False
        if self.difficulty < MINING_SHARE_MIN_DIFFICULTY or self.nonce < 0:
            return False
        if expected_job_id is not None and self.job_id != expected_job_id:
            return False
        if expected_difficulty is not None and self.difficulty != expected_difficulty:
            return False
        expected = self.calculate_hash()
        if self.share_hash != expected:
            return False
        if not expected.startswith("0" * self.difficulty):
            return False
        return self.share_id == self.calculate_id()

    def to_dict(self) -> Dict[str, Any]:
        return {
            "type": "mining_share",
            "miner": self.miner,
            "job_id": self.job_id,
            "difficulty": self.difficulty,
            "nonce": self.nonce,
            "share_hash": self.share_hash,
            "share_id": self.share_id or self.calculate_id(),
        }

    @staticmethod
    def from_dict(d: Dict[str, Any]) -> "MiningShare":
        return MiningShare(
            miner=d["miner"],
            job_id=d["job_id"],
            difficulty=int(d["difficulty"]),
            nonce=int(d["nonce"]),
            share_hash=d.get("share_hash", ""),
            share_id=d.get("share_id", ""),
        )


# ============================================================
# BLOCK
# ============================================================

@dataclass
class Block:
    index: int
    previous_hash: str
    transactions: List[Dict[str, Any]]
    timestamp: int
    nonce: int
    difficulty: int
    merkle_root: str
    extra_data: str
    block_hash: str = ""

    def header_dict(self) -> Dict[str, Any]:
        return {
            "index": self.index,
            "previous_hash": self.previous_hash,
            "merkle_root": self.merkle_root,
            "timestamp": self.timestamp,
            "nonce": self.nonce,
            "difficulty": self.difficulty,
            "extra_data": self.extra_data,
        }

    def calculate_hash(self) -> str:
        return hash_obj(self.header_dict())

    def mine(self, stop_event: Optional[threading.Event] = None) -> None:
        target = "0" * self.difficulty
        while True:
            if stop_event and stop_event.is_set():
                raise RuntimeError("mining interrupted")
            self.block_hash = self.calculate_hash()
            if self.block_hash.startswith(target):
                return
            self.nonce += 1

    def to_dict(self) -> Dict[str, Any]:
        return {
            **self.header_dict(),
            "hash": self.block_hash,
            "transactions": self.transactions,
        }

    @staticmethod
    def from_dict(d: Dict[str, Any]) -> "Block":
        return Block(
            index=int(d["index"]),
            previous_hash=d["previous_hash"],
            transactions=list(d["transactions"]),
            timestamp=int(d["timestamp"]),
            nonce=int(d["nonce"]),
            difficulty=int(d["difficulty"]),
            merkle_root=d["merkle_root"],
            extra_data=d.get("extra_data", ""),
            block_hash=d.get("hash", ""),
        )


# ============================================================
# BLOCKCHAIN / CONSENSUS
# ============================================================

def block_subsidy(block_index: int) -> int:
    """Return the consensus PoW subsidy for a block height.

    Block 0 is the fixed 25 EM genesis allocation. Mining subsidy starts
    at block 1 and halves every 1,445,400 blocks (27.5 years at 600 s/block).
    Integer base-unit rounding is consensus-critical.
    """
    if block_index <= 0:
        return BASE_REWARD
    halvings = block_index // HALVING_INTERVAL
    if halvings >= 64:
        return 0
    return INITIAL_BLOCK_REWARD >> halvings


class Blockchain:
    def __init__(
        self,
        node_port: int = 5000,
        db_file: Optional[str] = None,
        initial_difficulty: int = GENESIS_DIFFICULTY,
    ):
        self.node_port = node_port
        self.initial_difficulty = max(1, min(MAX_DIFFICULTY, int(initial_difficulty)))

        self.chain: List[Block] = []
        self.pending: Dict[str, Transaction] = {}
        self.orphans: Dict[str, Block] = {}

        self.balances: Dict[str, int] = {}
        self.nonces: Dict[str, int] = {}
        self.total_issued = 0
        self.total_burned = 0
        self.treasury_balance = 0
        self.miner_work: Dict[str, int] = {}
        self.wallet_tax_anchor: Dict[str, int] = {}
        self.pending_shares: Dict[str, Dict[str, Any]] = {}

        self.lock = threading.RLock()
        self.db_file = db_file or f"ca_state_{node_port}.json"

        if not self.load():
            self.create_genesis()

    # ---------- consensus economics ----------

    @property
    def circulating_supply(self) -> int:
        return self.total_issued - self.total_burned

    @property
    def height(self) -> int:
        return len(self.chain) - 1

    @property
    def treasury(self) -> int:
        return self.treasury_balance

    @property
    def pending_share_count(self) -> int:
        return len(self.pending_shares)

    @property
    def miner_work_total(self) -> int:
        return sum(w for w in self.miner_work.values() if w > 0)

    @property
    def cumulative_work(self) -> int:
        return self.chain_work(self.chain)

    @staticmethod
    def block_work(difficulty: int) -> int:
        # SHA3-512 has 512 bits. Requiring N leading zero hex digits
        # has an expected work of approximately 2^(4N).
        return 1 << (4 * difficulty)

    @classmethod
    def chain_work(cls, chain: List[Block]) -> int:
        return sum(cls.block_work(b.difficulty) for b in chain)

    def _credit(self, balances: Dict[str, int], address: str, amount: int) -> None:
        if amount < 0:
            raise ValueError("negative credit")
        balances[address] = balances.get(address, 0) + amount

    def _debit(self, balances: Dict[str, int], address: str, amount: int) -> None:
        if amount < 0:
            raise ValueError("negative debit")
        if balances.get(address, 0) < amount:
            raise ValueError("insufficient balance")
        balances[address] -= amount

    @staticmethod
    def _annual_tax_due(balance: int) -> int:
        if balance <= 0:
            return 0
        return (balance * (RECEIVER_TAX_BPS + TX_BURN_BPS)) // 10_000

    @staticmethod
    def _annual_tax_split(balance: int) -> Tuple[int, int]:
        """Return (Treasury tax, burned amount) for the annual 0.25% levy."""
        if balance <= 0:
            return 0, 0
        treasury_tax = (balance * RECEIVER_TAX_BPS) // 10_000
        burned = (balance * TX_BURN_BPS) // 10_000
        return treasury_tax, burned

    @staticmethod
    def _wallet_due(anchor: int, timestamp: int) -> bool:
        return timestamp >= anchor + YEAR_SECONDS

    @classmethod
    def _apply_annual_wallet_taxes(
        cls,
        balances: Dict[str, int],
        wallet_tax_anchor: Dict[str, int],
        treasury_balance: int,
        timestamp: int,
    ) -> Tuple[int, int, Dict[str, int]]:
        """Charge each wallet 0.25% of its full balance at each 365-day anniversary.

        Of the 0.25% levy, 0.20% goes to Treasury and 0.05% is burned.

        The anchor advances by exact 365-day periods, so missed anniversaries are
        deterministic and do not create an off-chain obligation. Empty wallets
        keep their anchor and simply advance when the annual cycle is reached.
        """
        anchors = dict(wallet_tax_anchor)
        total_burned = 0
        for address in sorted(anchors):
            anchor = int(anchors[address])
            if timestamp < anchor + YEAR_SECONDS:
                continue
            cycles = max(1, (timestamp - anchor) // YEAR_SECONDS)
            for _ in range(cycles):
                balance = int(balances.get(address, 0))
                if balance > 0:
                    treasury_tax, burned = cls._annual_tax_split(balance)
                    tax = treasury_tax + burned
                    if tax > balance:
                        tax = balance
                        # Preserve the intended split when integer rounding meets a tiny balance.
                        burned = min(burned, tax)
                        treasury_tax = tax - burned
                    balances[address] = balance - tax
                    treasury_balance += treasury_tax
                    total_burned += burned
                anchor += YEAR_SECONDS
            anchors[address] = anchor
        return treasury_balance, total_burned, anchors

    def next_nonce(self, address: str) -> int:
        with self.lock:
            confirmed = self.nonces.get(address, 0)
            pending = [
                tx.nonce for tx in self.pending.values()
                if tx.sender_address() == address
            ]
            return max([confirmed] + [n + 1 for n in pending])

    # ---------- deterministic difficulty ----------

    @staticmethod
    def expected_difficulty(chain: List[Block], next_height: int) -> int:
        if next_height == 0:
            return GENESIS_DIFFICULTY
        previous = chain[next_height - 1]
        difficulty = previous.difficulty

        if next_height % DIFFICULTY_INTERVAL != 0:
            return difficulty

        first_index = next_height - DIFFICULTY_INTERVAL
        first = chain[first_index]
        last = chain[next_height - 1]
        # The selected window contains DIFFICULTY_INTERVAL blocks, hence
        # DIFFICULTY_INTERVAL - 1 timestamp intervals between first and last.
        actual = max(1, last.timestamp - first.timestamp)
        expected = TARGET_BLOCK_TIME * max(1, DIFFICULTY_INTERVAL - 1)

        if actual < expected // 2:
            difficulty += 1
        elif actual > expected * 2:
            difficulty -= 1

        return max(MIN_DIFFICULTY, min(MAX_DIFFICULTY, difficulty))

    # ---------- time ----------

    @staticmethod
    def median_time_past(chain: List[Block]) -> int:
        timestamps = [b.timestamp for b in chain[-MTP_WINDOW:]]
        return sorted(timestamps)[len(timestamps) // 2]

    # ---------- genesis ----------

    def create_genesis(self) -> None:
        genesis_tx = {
            "type": "genesis",
            "tx_id": hash_obj({
                "message": GENESIS_MESSAGE,
                "recipient": "Miner_Genesis",
                "amount": BASE_REWARD,
            }),
            "recipient": "Miner_Genesis",
            "amount": BASE_REWARD,
            "memo": GENESIS_MESSAGE,
        }

        block = Block(
            index=0,
            previous_hash=ZERO_HASH,
            transactions=[genesis_tx],
            timestamp=0,
            nonce=0,
            difficulty=GENESIS_DIFFICULTY,
            merkle_root=MerkleTree.compute_root([genesis_tx["tx_id"]]),
            extra_data=GENESIS_MESSAGE,
        )
        block.mine()

        self.chain = [block]
        self.balances = {"Miner_Genesis": BASE_REWARD}
        self.nonces = {}
        self.total_issued = BASE_REWARD
        self.total_burned = 0
        self.treasury_balance = 0
        self.miner_work = {}
        # Genesis allocations participate in the same annual-tax cycle as every
        # other wallet; anchor them at genesis rather than creating an exemption.
        self.wallet_tax_anchor = {"Miner_Genesis": 0}
        self.save()

    # ---------- receiver tax / monthly treasury ----------

    @staticmethod
    def _apply_receiver_tax(amount: int) -> int:
        """Tax only the amount of an incoming payment."""
        if amount <= 0:
            return 0
        return (amount * RECEIVER_TAX_BPS) // 10_000

    @staticmethod
    def _distribute_treasury(
        balances: Dict[str, int],
        treasury_balance: int,
        miner_work: Dict[str, int],
    ) -> Tuple[int, Dict[str, int]]:
        """Empty Treasury at month-end and distribute it by verified PoW work."""
        if treasury_balance <= 0:
            return 0, {}

        positive = [(m, w) for m, w in miner_work.items() if w > 0]
        total_work = sum(w for _, w in positive)
        if total_work <= 0:
            # No verified work: keep Treasury for the next month rather than deleting it.
            return treasury_balance, dict(miner_work)

        distributed = 0
        for miner, work in sorted(positive):
            share = (treasury_balance * work) // total_work
            if share > 0:
                balances[miner] = balances.get(miner, 0) + share
                distributed += share

        dust = treasury_balance - distributed
        if dust:
            winner = max(positive, key=lambda x: (x[1], x[0]))[0]
            balances[winner] = balances.get(winner, 0) + dust
            distributed += dust

        return 0, {}

    @classmethod
    def _end_month_if_needed(
        cls,
        balances: Dict[str, int],
        treasury_balance: int,
        miner_work: Dict[str, int],
        block_index: int,
    ) -> Tuple[int, Dict[str, int]]:
        """At the end of each fixed 30-day block epoch, sweep Treasury to miners."""
        if block_index <= 0 or block_index % MINER_REWARD_EPOCH_BLOCKS != 0:
            return treasury_balance, miner_work
        return cls._distribute_treasury(balances, treasury_balance, miner_work)

    # ---------- transaction validation ----------

    def validate_transaction(
        self,
        tx: Transaction,
        balances: Optional[Dict[str, int]] = None,
        nonces: Optional[Dict[str, int]] = None,
        now: Optional[int] = None,
    ) -> Tuple[bool, str]:
        balances = self.balances if balances is None else balances
        nonces = self.nonces if nonces is None else nonces

        if not tx.is_valid(now=now):
            return False, "invalid signature, timestamp or encoding"

        sender = tx.sender_address()
        expected_nonce = nonces.get(sender, 0)

        if tx.nonce != expected_nonce:
            return False, f"invalid nonce: expected {expected_nonce}"

        if balances.get(sender, 0) < tx.amount:
            return False, "insufficient balance"

        return True, "ok"

    def add_mining_share(self, share: MiningShare) -> bool:
        with self.lock:
            expected_job_id = self.chain[-1].block_hash
            expected_difficulty = self.share_difficulty(self.chain[-1].difficulty)
            if not share.is_valid(expected_job_id=expected_job_id, expected_difficulty=expected_difficulty):
                return False
            if share.share_id in self.pending_shares:
                return False
            if len(self.pending_shares) >= MAX_PENDING_SHARES:
                return False
            self.pending_shares[share.share_id] = share.to_dict()
            self.save()
            return True

    def add_transaction(self, tx: Transaction) -> bool:
        with self.lock:
            if tx.tx_id in self.pending:
                return False

            ok, reason = self.validate_transaction(tx)
            if not ok:
                print(f"[TX ERROR] {reason}")
                return False

            sender = tx.sender_address()
            occupied = {
                p.nonce for p in self.pending.values()
                if p.sender_address() == sender
            }
            if tx.nonce in occupied:
                return False

            # Validate against confirmed state plus earlier pending txs.
            local_balances = dict(self.balances)
            local_nonces = dict(self.nonces)

            for p in sorted(
                self.pending.values(),
                key=lambda x: (x.sender_address(), x.nonce, x.tx_id)
            ):
                if p.sender_address() == sender and p.nonce >= tx.nonce:
                    continue
                ok, _ = self.validate_transaction(
                    p, local_balances, local_nonces, now=int(time.time())
                )
                if ok:
                    self._apply_transaction(p, local_balances, local_nonces)

            ok, reason = self.validate_transaction(
                tx, local_balances, local_nonces, now=int(time.time())
            )
            if not ok:
                print(f"[TX ERROR] {reason}")
                return False

            self.pending[tx.tx_id] = tx
            self.save()
            return True

    # ---------- state transition ----------

    @staticmethod
    def _apply_transaction(
        tx: Transaction,
        balances: Dict[str, int],
        nonces: Dict[str, int],
    ) -> Tuple[int, int]:
        sender = tx.sender_address()
        if nonces.get(sender, 0) != tx.nonce:
            raise ValueError("nonce mismatch")
        if balances.get(sender, 0) < tx.amount:
            raise ValueError("insufficient balance")

        receiver_tax = tx.receiver_tax()
        burned = tx.burned()
        balances[sender] -= tx.amount
        balances[tx.recipient] = balances.get(tx.recipient, 0) + tx.net_amount()
        nonces[sender] = tx.nonce + 1
        return burned, receiver_tax

    # ---------- special transactions ----------

    @staticmethod
    def reward_id(recipient: str, amount: int, issuance: int,
                  block_index: int) -> str:
        return hash_obj({
            "type": "reward",
            "recipient": recipient,
            "amount": amount,
            "issuance": issuance,
            "block_index": block_index,
        })

    @staticmethod
    def mining_share_id(share: Dict[str, Any]) -> str:
        return hash_obj({
            "type": "mining_share",
            "miner": share["miner"],
            "job_id": share["job_id"],
            "difficulty": int(share["difficulty"]),
            "nonce": int(share["nonce"]),
            "share_hash": share["share_hash"],
        })

    @staticmethod
    def share_difficulty(parent_difficulty: int) -> int:
        return max(MINING_SHARE_MIN_DIFFICULTY, parent_difficulty - SHARE_DIFFICULTY_OFFSET)

    @staticmethod
    def commitment_id(commitment: Dict[str, Any]) -> str:
        return hash_obj({
            "type": "l2_commitment",
            "root": commitment["root"],
            "count": commitment["count"],
            "first_sequence": commitment["first_sequence"],
            "last_sequence": commitment["last_sequence"],
            "state_root": commitment["state_root"],
        })

    # ---------- block validation / replay ----------

    def validate_block(
        self,
        block: Block,
        previous: Block,
        state_before: Tuple[Dict[str, int], Dict[str, int], int, int, int, Dict[str, int], Dict[str, int]],
        chain_prefix: List[Block],
        now: Optional[int] = None,
    ) -> Tuple[bool, str, Tuple[Dict[str, int], Dict[str, int], int, int, int, Dict[str, int], Dict[str, int]]]:
        now = int(time.time()) if now is None else now
        balances, nonces, total_issued, total_burned, treasury_balance, miner_work, wallet_tax_anchor = (
            dict(state_before[0]), dict(state_before[1]), int(state_before[2]), int(state_before[3]),
            int(state_before[4]), dict(state_before[5]), dict(state_before[6]),
        )

        if block.index != previous.index + 1:
            return False, "invalid index", state_before
        if block.previous_hash != previous.block_hash:
            return False, "invalid previous hash", state_before
        if not (MIN_DIFFICULTY <= block.difficulty <= MAX_DIFFICULTY):
            return False, "invalid difficulty", state_before

        expected_d = self.expected_difficulty(
            chain_prefix, block.index
        )
        if block.difficulty != expected_d:
            return False, "unexpected difficulty", state_before

        if block.timestamp < self.median_time_past(chain_prefix):
            return False, "timestamp below median-time-past", state_before
        if block.timestamp > now + MAX_FUTURE_BLOCK_TIME:
            return False, "timestamp too far in future", state_before

        if len(block.transactions) < 1:
            return False, "empty block", state_before
        if len(block.transactions) > MAX_TX_PER_BLOCK + MAX_SHARES_PER_BLOCK + 2:
            return False, "too many transactions", state_before

        serialized_size = len(canonical_json(block.to_dict()))
        if serialized_size > MAX_BLOCK_BYTES:
            return False, "block too large", state_before

        ids = []
        for raw in block.transactions:
            txid = raw.get("tx_id") or raw.get("share_id")
            if not isinstance(txid, str):
                return False, "transaction missing id", state_before
            ids.append(txid)

        if block.merkle_root != MerkleTree.compute_root(ids):
            return False, "invalid Merkle root", state_before
        if block.calculate_hash() != block.block_hash:
            return False, "invalid block hash", state_before
        if not block.block_hash.startswith("0" * block.difficulty):
            return False, "invalid proof of work", state_before

        reward = block.transactions[-1]
        if reward.get("type") != "reward":
            return False, "reward must be last", state_before

        miner = reward.get("recipient")
        if not isinstance(miner, str) or len(miner) != 128 or not is_hex(miner, 128):
            return False, "invalid miner address", state_before

        seen = set()
        transfer_burn = 0
        l2_count = 0
        share_count = 0
        expected_share_job = previous.block_hash
        expected_share_difficulty = self.share_difficulty(previous.difficulty)

        for raw in block.transactions[:-1]:
            tx_type = raw.get("type")

            if tx_type == "transfer":
                tx = Transaction.from_dict(raw)
                if tx.tx_id in seen:
                    return False, "duplicate transaction", state_before
                seen.add(tx.tx_id)

                if not tx.is_valid(now=now):
                    return False, "invalid transaction", state_before

                try:
                    burned, receiver_tax = self._apply_transaction(tx, balances, nonces)
                    transfer_burn += burned
                    treasury_balance += receiver_tax
                    if tx.recipient not in wallet_tax_anchor:
                        wallet_tax_anchor[tx.recipient] = block.timestamp
                except ValueError as e:
                    return False, str(e), state_before

            elif tx_type == "mining_share":
                try:
                    share = MiningShare.from_dict(raw)
                except (KeyError, ValueError, TypeError):
                    return False, "invalid mining share encoding", state_before
                if share_count >= MAX_SHARES_PER_BLOCK:
                    return False, "too many mining shares", state_before
                if share.share_id in seen:
                    return False, "duplicate mining share", state_before
                if not share.is_valid(expected_job_id=expected_share_job, expected_difficulty=expected_share_difficulty):
                    return False, "invalid mining share proof", state_before
                if share.share_id != self.mining_share_id(raw):
                    return False, "invalid mining share id", state_before
                # A share is worth a fixed, verifiable amount of PoW work.
                miner_work[share.miner] = miner_work.get(share.miner, 0) + self.block_work(share.difficulty)
                seen.add(share.share_id)
                share_count += 1

            elif tx_type == "l2_commitment":
                expected_id = self.commitment_id(raw)
                if raw.get("tx_id") != expected_id:
                    return False, "invalid L2 commitment id", state_before
                if raw.get("tx_id") in seen:
                    return False, "duplicate L2 commitment", state_before
                seen.add(raw["tx_id"])
                l2_count += 1

            else:
                return False, "invalid transaction type", state_before

        issuance = min(block_subsidy(block.index), MAX_SUPPLY - total_issued)
        if issuance < 0:
            return False, "negative issuance", state_before

        # Treasury distributions are ordinary transfers from existing supply,
        # never new issuance. They are applied by _apply_economic_cycle above.
        expected_reward = issuance

        if int(reward.get("issuance", -1)) != issuance:
            return False, "invalid reward issuance", state_before
        if int(reward.get("amount", -1)) != expected_reward:
            return False, "invalid miner reward", state_before

        expected_reward_id = self.reward_id(
            miner, expected_reward, issuance, block.index
        )
        if reward.get("tx_id") != expected_reward_id:
            return False, "invalid reward id", state_before

        total_issued += issuance
        total_burned += transfer_burn

        if total_issued > MAX_SUPPLY:
            return False, "hard issuance cap exceeded", state_before
        if total_burned > total_issued:
            return False, "burn exceeds issuance", state_before

        self._credit(balances, miner, expected_reward)
        if miner not in wallet_tax_anchor:
            wallet_tax_anchor[miner] = block.timestamp
        miner_work[miner] = miner_work.get(miner, 0) + self.block_work(block.difficulty)

        # Apply deterministic annual wallet taxes before the monthly Treasury sweep.
        treasury_balance, annual_burned, wallet_tax_anchor = self._apply_annual_wallet_taxes(
            balances, wallet_tax_anchor, treasury_balance, block.timestamp
        )
        total_burned += annual_burned
        if total_burned > total_issued:
            return False, "burn exceeds issuance", state_before

        # Count the closing block's verified PoW, then sweep the entire Treasury.
        treasury_balance, miner_work = self._end_month_if_needed(
            balances, treasury_balance, miner_work, block.index
        )

        return True, "ok", (
            balances, nonces, total_issued, total_burned,
            treasury_balance, miner_work, wallet_tax_anchor
        )

    def replay_chain(
        self, chain: List[Block]
    ) -> Tuple[bool, str, Tuple[Dict[str, int], Dict[str, int], int, int, int, Dict[str, int], Dict[str, int]]]:
        if not chain:
            return False, "empty chain", ({}, {}, 0, 0, 0, {})

        genesis = chain[0]
        expected_genesis_tx = {
            "type": "genesis",
            "tx_id": hash_obj({
                "message": GENESIS_MESSAGE,
                "recipient": "Miner_Genesis",
                "amount": BASE_REWARD,
            }),
            "recipient": "Miner_Genesis",
            "amount": BASE_REWARD,
            "memo": GENESIS_MESSAGE,
        }

        if genesis.index != 0 or genesis.previous_hash != ZERO_HASH:
            return False, "invalid genesis linkage", ({}, {}, 0, 0, 0, {})
        if genesis.difficulty != GENESIS_DIFFICULTY:
            return False, "invalid genesis difficulty", ({}, {}, 0, 0, 0, {})
        if genesis.timestamp != 0:
            return False, "invalid genesis timestamp", ({}, {}, 0, 0, 0, {})
        if genesis.transactions != [expected_genesis_tx]:
            return False, "genesis contents mismatch", ({}, {}, 0, 0, 0, {})
        if genesis.merkle_root != MerkleTree.compute_root([expected_genesis_tx["tx_id"]]):
            return False, "invalid genesis merkle root", ({}, {}, 0, 0, 0, {})
        if genesis.calculate_hash() != genesis.block_hash:
            return False, "invalid genesis hash", ({}, {}, 0, 0, 0, {})
        if not genesis.block_hash.startswith("0" * GENESIS_DIFFICULTY):
            return False, "invalid genesis proof of work", ({}, {}, 0, 0, 0, {})

        balances = {"Miner_Genesis": BASE_REWARD}
        nonces: Dict[str, int] = {}
        state = (balances, nonces, BASE_REWARD, 0, 0, {}, {})

        for i in range(1, len(chain)):
            block = chain[i]
            previous = chain[i - 1]
            ok, reason, state = self.validate_block(
                block, previous, state, chain[:i]
            )
            if not ok:
                return False, f"block {i}: {reason}", state

        return True, "ok", state

    def validate_chain(self, chain: List[Block]) -> Tuple[bool, str]:
        ok, reason, _ = self.replay_chain(chain)
        return ok, reason

    # ---------- mining ----------

    def build_candidate_block(
        self,
        miner_address: str,
        l2_commitments: Optional[List[Dict[str, Any]]] = None,
    ) -> Block:
        with self.lock:
            if not is_hex(miner_address, 128):
                raise ValueError("invalid miner address")

            balances = dict(self.balances)
            nonces = dict(self.nonces)
            treasury_balance = self.treasury_balance
            miner_work = dict(self.miner_work)

            selected: List[Transaction] = []
            local_nonces = dict(nonces)

            # Deterministic ordering. Receiver tax is calculated during block replay
            # from each transfer amount and is therefore not a wallet-balance tax.
            for tx in sorted(
                self.pending.values(),
                key=lambda x: (x.timestamp, x.sender_address(), x.nonce, x.tx_id)
            ):
                sender = tx.sender_address()
                if local_nonces.get(sender, 0) != tx.nonce:
                    continue
                if balances.get(sender, 0) < tx.amount:
                    continue
                if not tx.is_valid():
                    continue
                self._apply_transaction(tx, balances, local_nonces)
                selected.append(tx)
                if len(selected) >= MAX_TX_PER_BLOCK:
                    break

            data_txs: List[Dict[str, Any]] = [
                {"type": "transfer", **tx.to_dict()} for tx in selected
            ]

            if l2_commitments:
                for c in l2_commitments:
                    c = dict(c)
                    c["type"] = "l2_commitment"
                    c["tx_id"] = self.commitment_id(c)
                    data_txs.append(c)

            expected_job_id = self.chain[-1].block_hash
            expected_share_difficulty = self.share_difficulty(self.chain[-1].difficulty)
            share_items = []
            for sid, raw in sorted(self.pending_shares.items(), key=lambda kv: kv[0]):
                try:
                    share = MiningShare.from_dict(raw)
                except (KeyError, ValueError, TypeError):
                    continue
                if share.is_valid(expected_job_id=expected_job_id, expected_difficulty=expected_share_difficulty):
                    share_items.append(raw)
                if len(share_items) >= MAX_SHARES_PER_BLOCK:
                    break
            data_txs.extend(share_items)

            next_height = len(self.chain)
            difficulty = self.expected_difficulty(self.chain, next_height)

            issuance = min(block_subsidy(next_height), MAX_SUPPLY - self.total_issued)
            reward_amount = issuance
            reward = {
                "type": "reward",
                "tx_id": self.reward_id(
                    miner_address, reward_amount, issuance, next_height
                ),
                "recipient": miner_address,
                "amount": reward_amount,
                "issuance": issuance,
            }
            tx_dicts = data_txs + [reward]

            timestamp = max(
                int(time.time()),
                self.median_time_past(self.chain)
            )

            block = Block(
                index=next_height,
                previous_hash=self.chain[-1].block_hash,
                transactions=tx_dicts,
                timestamp=timestamp,
                nonce=0,
                difficulty=difficulty,
                merkle_root=MerkleTree.compute_root(
                    [x.get("tx_id") or x.get("share_id") for x in tx_dicts]
                ),
                extra_data=f"ELECTRIC-MONEY-PoW-{NETWORK_ID}",
            )
            return block

    def mine_pending(
        self,
        miner_address: str,
        l2_commitments: Optional[List[Dict[str, Any]]] = None,
        stop_event: Optional[threading.Event] = None,
    ) -> Block:
        block = self.build_candidate_block(miner_address, l2_commitments)

        block.mine(stop_event)

        with self.lock:
            if block.previous_hash != self.chain[-1].block_hash:
                raise RuntimeError("tip changed while mining")

            ok, reason, new_state = self.validate_block(
                block,
                self.chain[-1],
                (
                    self.balances,
                    self.nonces,
                    self.total_issued,
                    self.total_burned,
                    self.treasury_balance,
                    self.miner_work,
                    self.wallet_tax_anchor,
                ),
                self.chain,
            )
            if not ok:
                raise RuntimeError(f"self-mined block rejected: {reason}")

            self.chain.append(block)
            (
                self.balances, self.nonces, self.total_issued, self.total_burned,
                self.treasury_balance, self.miner_work, self.wallet_tax_anchor
            ) = new_state

            confirmed_ids = {
                raw.get("tx_id")
                for raw in block.transactions
                if raw.get("type") == "transfer"
            }
            self.pending = {
                txid: tx for txid, tx in self.pending.items()
                if txid not in confirmed_ids
            }
            for raw in block.transactions:
                if raw.get("type") == "mining_share":
                    self.pending_shares.pop(raw.get("share_id"), None)
            # All remaining shares were mined against the old tip and are now stale.
            self.pending_shares = {
                sid: raw for sid, raw in self.pending_shares.items()
                if raw.get("job_id") == self.chain[-1].block_hash
            }
            self.save()
            return block

    # ---------- fork / reorg ----------

    def _find_candidate_from_orphan(self, block: Block) -> Optional[List[Block]]:
        path = [block]
        current = block
        known = dict(self.orphans)

        while current.previous_hash != self.chain[-1].block_hash:
            # If the parent is on our canonical chain, we can reconstruct
            # a candidate from the common ancestor.
            parent_index = next(
                (i for i, b in enumerate(self.chain)
                 if b.block_hash == current.previous_hash),
                None
            )
            if parent_index is not None:
                return self.chain[:parent_index + 1] + list(reversed(path))

            parent = known.get(current.previous_hash)
            if parent is None:
                return None

            path.append(parent)
            current = parent

        return self.chain + list(reversed(path))

    def receive_block(self, block: Block) -> str:
        with self.lock:
            if block.block_hash in {b.block_hash for b in self.chain}:
                return "known"

            self.orphans[block.block_hash] = block
            if len(self.orphans) > MAX_ORPHANS:
                # Deterministic bounded eviction: remove the lexicographically
                # smallest hash. Orphans are disposable and will be requested again
                # if a peer still has the missing branch.
                oldest = sorted(self.orphans)[0]
                self.orphans.pop(oldest, None)

            candidate = self._find_candidate_from_orphan(block)
            if candidate is None:
                return "orphan"

            ok, reason = self.validate_chain(candidate)
            if not ok:
                self.orphans.pop(block.block_hash, None)
                return f"rejected:{reason}"

            if self.chain_work(candidate) <= self.chain_work(self.chain):
                return "valid-lighter"

            old_chain = self.chain
            self.chain = candidate
            ok, reason, state = self.replay_chain(candidate)
            if not ok:
                self.chain = old_chain
                return f"rejected:{reason}"

            (
                self.balances, self.nonces, self.total_issued, self.total_burned,
                self.treasury_balance, self.miner_work, self.wallet_tax_anchor
            ) = state

            confirmed = {
                raw.get("tx_id")
                for b in candidate
                for raw in b.transactions
                if raw.get("type") == "transfer"
            }
            self.pending = {
                txid: tx for txid, tx in self.pending.items()
                if txid not in confirmed
            }
            for raw in candidate[-1].transactions:
                if raw.get("type") == "mining_share":
                    self.pending_shares.pop(raw.get("share_id"), None)

            for h in list(self.orphans):
                if h in {b.block_hash for b in candidate}:
                    self.orphans.pop(h, None)

            self.save()
            return "reorged"

    def try_replace_chain(self, candidate: List[Block]) -> bool:
        with self.lock:
            if self.chain_work(candidate) <= self.chain_work(self.chain):
                return False

            ok, reason = self.validate_chain(candidate)
            if not ok:
                print(f"[CONSENSUS] Candidate rejected: {reason}")
                return False

            # Preserve transfer transactions from the old main chain so transactions
            # orphaned by the reorg can be reconsidered for the mempool.
            old_transfer_txs = {
                raw["tx_id"]: raw
                for b in self.chain
                for raw in b.transactions
                if raw.get("type") == "transfer" and isinstance(raw.get("tx_id"), str)
            }
            old_chain = self.chain
            old_state = (
                dict(self.balances), dict(self.nonces), self.total_issued, self.total_burned,
                self.treasury_balance, dict(self.miner_work), dict(self.wallet_tax_anchor)
            )
            self.chain = candidate
            ok, replay_reason, state = self.replay_chain(candidate)
            if not ok:
                self.chain = old_chain
                (
                    self.balances, self.nonces, self.total_issued, self.total_burned,
                    self.treasury_balance, self.miner_work, self.wallet_tax_anchor
                ) = old_state
                print(f"[CONSENSUS] Replay failed after validation: {replay_reason}")
                return False
            (
                self.balances, self.nonces, self.total_issued, self.total_burned,
                self.treasury_balance, self.miner_work, self.wallet_tax_anchor
            ) = state

            new_confirmed = {
                raw.get("tx_id")
                for b in candidate
                for raw in b.transactions
                if raw.get("type") == "transfer"
            }

            # Re-add only transactions that disappeared from the winning chain.
            # add_transaction() revalidates signature, nonce, balance and mempool rules.
            orphaned_ids = set(old_transfer_txs) - new_confirmed
            for txid in sorted(orphaned_ids):
                try:
                    tx = Transaction.from_dict(old_transfer_txs[txid])
                    if txid not in self.pending:
                        self.add_transaction(tx)
                except Exception as exc:
                    print(f"[REORG] discarded orphaned tx {txid}: {exc}")

            # Shares are tied to a specific parent-job (the previous block hash).
            # Shares from the losing branch therefore become stale after a reorg and
            # are deliberately NOT replayed into the new branch.
            self.pending_shares = {
                sid: raw for sid, raw in self.pending_shares.items()
                if raw.get("job_id") == candidate[-1].block_hash
            }

            self.save()
            return True

    # ---------- persistence ----------

    def save(self) -> None:
        with self.lock:
            data = {
                "network_id": NETWORK_ID,
                "protocol_version": PROTOCOL_VERSION,
                "chain": [b.to_dict() for b in self.chain],
                "pending": [tx.to_dict() for tx in self.pending.values()],
                "pending_shares": list(self.pending_shares.values()),
                "orphans": [b.to_dict() for b in self.orphans.values()],
            }
            tmp = self.db_file + ".tmp"
            with open(tmp, "w", encoding="utf-8") as f:
                json.dump(data, f, indent=2, ensure_ascii=False)
            os.replace(tmp, self.db_file)

    def load(self) -> bool:
        try:
            with open(self.db_file, "r", encoding="utf-8") as f:
                data = json.load(f)

            if data.get("network_id", NETWORK_ID) != NETWORK_ID:
                return False

            chain = [Block.from_dict(x) for x in data["chain"]]
            ok, reason, state = self.replay_chain(chain)
            if not ok:
                print(f"[DB ERROR] Stored chain rejected: {reason}")
                return False

            self.chain = chain
            (
                self.balances, self.nonces, self.total_issued, self.total_burned,
                self.treasury_balance, self.miner_work, self.wallet_tax_anchor
            ) = state


            self.pending_shares = {
                raw.get("share_id"): raw
                for raw in data.get("pending_shares", [])
                if isinstance(raw, dict) and raw.get("share_id")
            }
            self.pending = {}
            for raw in data.get("pending", []):
                tx = Transaction.from_dict(raw)
                if self.validate_transaction(tx)[0]:
                    self.pending[tx.tx_id] = tx

            loaded_orphans: Dict[str, Block] = {}
            for raw in data.get("orphans", []):
                if len(loaded_orphans) >= MAX_ORPHANS:
                    break
                try:
                    b = Block.from_dict(raw)
                    if b.calculate_hash() == b.block_hash:
                        loaded_orphans[b.block_hash] = b
                except (KeyError, TypeError, ValueError):
                    continue
            self.orphans = loaded_orphans
            return True
        except (
            FileNotFoundError, KeyError, ValueError, TypeError,
            json.JSONDecodeError, OSError
        ):
            return False


def make_mining_share(miner_address: str, job_id: str, difficulty: int, nonce: int) -> MiningShare:
    share = MiningShare(miner=miner_address, job_id=job_id, difficulty=difficulty, nonce=nonce)
    share.share_hash = share.calculate_hash()
    share.share_id = share.calculate_id()
    return share


# ============================================================
# L2
# ============================================================

@dataclass
class L2Transaction:
    sender_pubkey: str
    recipient: str
    amount: int
    nonce: int
    timestamp: int
    signature: str = ""
    tx_id: str = ""

    def sender(self) -> str:
        return Wallet.address_from_pubkey(self.sender_pubkey)

    def signing_dict(self) -> Dict[str, Any]:
        return {
            "sender_pubkey": self.sender_pubkey,
            "recipient": self.recipient,
            "amount": self.amount,
            "nonce": self.nonce,
            "timestamp": self.timestamp,
        }

    def signing_bytes(self) -> bytes:
        return canonical_json(self.signing_dict())

    def calculate_id(self) -> str:
        return hash_obj({
            **self.signing_dict(),
            "signature": self.signature,
        })

    def valid(self) -> bool:
        return (
            self.amount > 0
            and is_hex(self.sender_pubkey, 128)
            and is_hex(self.recipient, 128)
            and self.signature != ""
            and self.tx_id == self.calculate_id()
            and Wallet.verify(
                self.sender_pubkey, self.signing_bytes(), self.signature
            )
        )

    def to_dict(self) -> Dict[str, Any]:
        return {
            **self.signing_dict(),
            "signature": self.signature,
            "tx_id": self.tx_id,
        }


class Layer2Sequencer:
    """
    Reference L2.

    L1 does NOT execute this state transition. L1 only commits the batch root
    and state root. Therefore this is not a trustless rollup.

    Deposit model:
      - an L1 user sends CA to L2_BRIDGE_ADDRESS through a normal L1 transfer
      - after confirmation, the sequencer can credit the corresponding net amount
      - withdrawals are operator-controlled in this prototype
    """

    def __init__(self, l1: Blockchain):
        self.l1 = l1
        self.balances: Dict[str, int] = {}
        self.nonces: Dict[str, int] = {}
        self.mempool: List[L2Transaction] = []
        self.sequence = 0
        self.poh_hash = sha3_512_hex(b"EM_L2_POH_GENESIS")
        self.pending_commitments: List[Dict[str, Any]] = []

    def _state_root(self) -> str:
        state = {
            "balances": dict(sorted(self.balances.items())),
            "nonces": dict(sorted(self.nonces.items())),
        }
        return hash_obj(state)

    def process_l1_deposit(self, address: str, amount: int) -> bool:
        if amount <= 0:
            return False
        # The caller is expected to have observed a confirmed L1 transfer
        # to the bridge. We do not mutate L1 state here.
        self.balances[address] = self.balances.get(address, 0) + amount
        return True

    def add_signed_tx(self, tx: L2Transaction) -> bool:
        if not tx.valid():
            return False

        sender = tx.sender()
        if tx.nonce != self.nonces.get(sender, 0):
            return False
        if self.balances.get(sender, 0) < tx.amount:
            return False

        self.balances[sender] -= tx.amount
        self.balances[tx.recipient] = self.balances.get(tx.recipient, 0) + tx.amount
        self.nonces[sender] = tx.nonce + 1

        self.sequence += 1
        self.poh_hash = sha3_512_hex(
            (self.poh_hash + tx.tx_id).encode("ascii")
        )
        self.mempool.append(tx)
        return True

    def commit_batch(self) -> Optional[Dict[str, Any]]:
        if not self.mempool:
            return None

        ids = [tx.tx_id for tx in self.mempool]
        commitment = {
            "root": MerkleTree.compute_root(ids),
            "count": len(ids),
            "first_sequence": self.sequence - len(ids) + 1,
            "last_sequence": self.sequence,
            "state_root": self._state_root(),
        }
        self.mempool.clear()
        self.pending_commitments.append(commitment)
        return commitment

    def take_commitments(self) -> List[Dict[str, Any]]:
        result = list(self.pending_commitments)
        self.pending_commitments.clear()
        return result


# ============================================================
# P2P
# ============================================================

def send_frame(conn: socket.socket, obj: Any) -> None:
    payload = canonical_json(obj)
    if len(payload) > MAX_FRAME_BYTES:
        raise ValueError("message too large")
    conn.sendall(struct.pack("!I", len(payload)) + payload)


def _recv_exact(conn: socket.socket, n: int) -> bytes:
    chunks = []
    remaining = n
    while remaining:
        chunk = conn.recv(remaining)
        if not chunk:
            return b""
        chunks.append(chunk)
        remaining -= len(chunk)
    return b"".join(chunks)


def recv_frame(conn: socket.socket) -> Optional[Any]:
    header = _recv_exact(conn, 4)
    if not header:
        return None
    length = struct.unpack("!I", header)[0]
    if length <= 0 or length > MAX_FRAME_BYTES:
        raise ValueError("invalid frame size")
    payload = _recv_exact(conn, length)
    if not payload:
        return None
    return json.loads(payload.decode("utf-8"))


def parse_peer(value: str) -> Tuple[str, int]:
    host, port = value.rsplit(":", 1)
    return host, int(port)


class P2PNode:
    def __init__(
        self,
        bc: Blockchain,
        host: str = "0.0.0.0",
        port: int = 5000,
        peers: Optional[List[str]] = None,
        node_id: Optional[str] = None,
    ):
        self.bc = bc
        self.host = host
        self.port = port
        self.node_id = node_id or secrets.token_hex(16)
        self.peers = set()
        for peer in (peers or []):
            try:
                host, port = parse_peer(peer)
                if host and 1 <= port <= 65535 and len(self.peers) < MAX_PEERS:
                    self.peers.add(f"{host}:{port}")
            except (ValueError, TypeError):
                continue
        self.running = False
        self.server: Optional[socket.socket] = None

        self.seen_txs: set = set()
        self.seen_shares: set = set()
        self.seen_blocks: set = set()
        self.peer_lock = threading.RLock()
        self.connection_slots = threading.BoundedSemaphore(64)

    def hello(self) -> Dict[str, Any]:
        return {
            "type": "HELLO",
            "protocol_version": PROTOCOL_VERSION,
            "network_id": NETWORK_ID,
            "node_id": self.node_id,
            "height": self.bc.height,
            "tip": self.bc.chain[-1].block_hash,
            "work": str(self.bc.cumulative_work),
        }

    def start(self) -> None:
        if self.running:
            return

        self.server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self.server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        self.server.bind((self.host, self.port))
        self.server.listen(64)
        self.running = True

        threading.Thread(target=self._accept_loop, daemon=True).start()
        threading.Thread(target=self._peer_loop, daemon=True).start()

        print(
            f"[P2P] node={self.node_id} listening on "
            f"{self.host}:{self.port}, peers={sorted(self.peers)}"
        )

    def stop(self) -> None:
        self.running = False
        if self.server:
            try:
                self.server.close()
            except OSError:
                pass

    def _accept_loop(self) -> None:
        assert self.server is not None
        while self.running:
            try:
                conn, addr = self.server.accept()
                if not self.connection_slots.acquire(blocking=False):
                    conn.close()
                    continue
                threading.Thread(
                    target=self._handle_connection,
                    args=(conn, addr),
                    daemon=True,
                ).start()
            except OSError:
                break

    def _peer_loop(self) -> None:
        while self.running:
            for peer in list(self.peers):
                try:
                    self._connect(peer)
                except Exception:
                    pass
            time.sleep(5)

    def _connect(self, peer: str) -> None:
        host, port = parse_peer(peer)
        with socket.create_connection((host, port), timeout=3) as conn:
            conn.settimeout(8)
            send_frame(conn, self.hello())
            reply = recv_frame(conn)
            if reply:
                self._process_message(reply, conn, peer)

    def _handle_connection(
        self, conn: socket.socket, addr: Tuple[str, int]
    ) -> None:
        conn.settimeout(10)
        peer_name = f"{addr[0]}:{addr[1]}"
        try:
            msg = recv_frame(conn)
            if msg:
                self._process_message(msg, conn, peer_name)
        except Exception as e:
            print(f"[P2P] {peer_name}: {e}")
        finally:
            try:
                conn.close()
            except OSError:
                pass
            finally:
                self.connection_slots.release()

    def _process_message(
        self,
        msg: Dict[str, Any],
        conn: socket.socket,
        peer_name: str,
    ) -> None:
        if not isinstance(msg, dict):
            return
        mtype = msg.get("type")

        if mtype == "HELLO":
            if msg.get("network_id") != NETWORK_ID:
                return
            if int(msg.get("protocol_version", -1)) != PROTOCOL_VERSION:
                return
            remote_node_id = msg.get("node_id")
            if not isinstance(remote_node_id, str) or not remote_node_id or remote_node_id == self.node_id:
                return

            remote_work = int(msg.get("work", "0"))
            send_frame(conn, self.hello())

            if remote_work > self.bc.cumulative_work:
                send_frame(conn, {
                    "type": "GET_CHAIN",
                    "from_height": 0,
                })
            return

        if mtype == "GET_CHAIN":
            send_frame(conn, {
                "type": "CHAIN",
                "chain": [b.to_dict() for b in self.bc.chain],
            })
            return

        if mtype == "CHAIN":
            raw_chain = msg.get("chain", [])
            if not isinstance(raw_chain, list):
                return
            try:
                candidate = [Block.from_dict(x) for x in raw_chain]
            except (KeyError, TypeError, ValueError):
                return
            if self.bc.try_replace_chain(candidate):
                print(
                    f"[P2P] adopted heavier chain height={self.bc.height} "
                    f"work={self.bc.cumulative_work}"
                )
            return

        if mtype == "TX":
            try:
                tx = Transaction.from_dict(msg["tx"])
            except (KeyError, TypeError, ValueError):
                return
            if tx.tx_id in self.seen_txs:
                return
            self.seen_txs.add(tx.tx_id)
            if self.bc.add_transaction(tx):
                self.broadcast_tx(tx, exclude=peer_name)
            return

        if mtype == "SHARE":
            try:
                share = MiningShare.from_dict(msg["share"])
            except (KeyError, ValueError, TypeError):
                return
            if share.share_id in self.seen_shares:
                return
            if self.bc.add_mining_share(share):
                self.seen_shares.add(share.share_id)
                self.broadcast_share(share, exclude=peer_name)
            return

        if mtype == "BLOCK":
            try:
                block = Block.from_dict(msg["block"])
            except (KeyError, TypeError, ValueError):
                return
            if block.block_hash in self.seen_blocks:
                return
            self.seen_blocks.add(block.block_hash)

            result = self.bc.receive_block(block)
            if result in ("reorged", "known", "valid-lighter"):
                self.broadcast_block(block, exclude=peer_name)
            elif result == "orphan":
                # Ask the peer for the full chain; validation will decide.
                try:
                    send_frame(conn, {"type": "GET_CHAIN", "from_height": 0})
                except Exception:
                    pass
            return

        if mtype == "PING":
            send_frame(conn, {"type": "PONG"})
            return

    def _send_peer(self, peer: str, message: Dict[str, Any]) -> None:
        host, port = parse_peer(peer)
        try:
            with socket.create_connection((host, port), timeout=3) as conn:
                conn.settimeout(8)
                send_frame(conn, message)
        except OSError:
            pass

    def broadcast_tx(self, tx: Transaction, exclude: Optional[str] = None) -> None:
        message = {"type": "TX", "tx": tx.to_dict()}
        for peer in list(self.peers):
            if peer != exclude:
                threading.Thread(
                    target=self._send_peer,
                    args=(peer, message),
                    daemon=True,
                ).start()

    def broadcast_share(self, share: MiningShare, exclude: Optional[str] = None) -> None:
        message = {"type": "SHARE", "share": share.to_dict()}
        for peer in list(self.peers):
            if peer != exclude:
                threading.Thread(
                    target=self._send_peer,
                    args=(peer, message),
                    daemon=True,
                ).start()

    def broadcast_block(self, block: Block, exclude: Optional[str] = None) -> None:
        message = {"type": "BLOCK", "block": block.to_dict()}
        for peer in list(self.peers):
            if peer != exclude:
                threading.Thread(
                    target=self._send_peer,
                    args=(peer, message),
                    daemon=True,
                ).start()

    def broadcast_chain(self) -> None:
        message = {
            "type": "CHAIN",
            "chain": [b.to_dict() for b in self.bc.chain],
        }
        for peer in list(self.peers):
            threading.Thread(
                target=self._send_peer,
                args=(peer, message),
                daemon=True,
            ).start()


# ============================================================
# HELPERS / DEMO / TESTS
# ============================================================

def make_transfer(
    wallet: Wallet,
    recipient: str,
    amount_ca: int,
    nonce: int,
) -> Transaction:
    tx = Transaction(
        sender_pubkey=wallet.public_key_hex,
        recipient=recipient,
        amount=amount_ca * COIN,
        nonce=nonce,
        timestamp=int(time.time()),
    )
    wallet.sign_transaction(tx)
    return tx


def self_test() -> None:
    import tempfile

    with tempfile.TemporaryDirectory() as td:
        db = str(Path(td) / "node.json")
        bc = Blockchain(node_port=0, db_file=db)
        alice = Wallet()
        bob = Wallet()
        miner = Wallet()

        # Subsidy schedule: initial reward, exact halving boundary, and later eras.
        assert block_subsidy(1) == INITIAL_BLOCK_REWARD
        assert block_subsidy(HALVING_INTERVAL - 1) == INITIAL_BLOCK_REWARD
        assert block_subsidy(HALVING_INTERVAL) == INITIAL_BLOCK_REWARD // 2
        assert block_subsidy(HALVING_INTERVAL * 2) == INITIAL_BLOCK_REWARD // 4

        # A real reward establishes Alice's first on-chain wallet tax anchor.
        funding_block = bc.mine_pending(alice.address)
        assert funding_block.index == 1
        assert bc.balances[alice.address] == INITIAL_BLOCK_REWARD
        assert bc.wallet_tax_anchor[alice.address] == funding_block.timestamp

        # Every incoming payment is taxed independently; existing balance is not taxed.
        tx = make_transfer(alice, bob.address, 10, bc.next_nonce(alice.address))
        assert bc.add_transaction(tx)
        bc.mine_pending(miner.address)
        expected_treasury = (10 * COIN * RECEIVER_TAX_BPS) // 10_000
        expected_burn = (10 * COIN * TX_BURN_BPS) // 10_000
        assert tx.receiver_tax() == expected_treasury
        assert tx.burned() == expected_burn
        assert bc.balances[bob.address] == 10 * COIN - expected_treasury - expected_burn
        assert bc.treasury_balance == expected_treasury
        assert bc.total_burned == expected_burn
        assert bc.balances[alice.address] == INITIAL_BLOCK_REWARD - 10 * COIN

        # A second payment creates a second independent incoming tax.
        second = make_transfer(alice, bob.address, 5, bc.next_nonce(alice.address))
        assert bc.add_transaction(second)
        bc.mine_pending(miner.address)
        second_treasury = (5 * COIN * RECEIVER_TAX_BPS) // 10_000
        second_burn = (5 * COIN * TX_BURN_BPS) // 10_000
        assert bc.balances[bob.address] == 15 * COIN - expected_treasury - expected_burn - second_treasury - second_burn
        assert bc.treasury_balance == expected_treasury + second_treasury
        assert bc.total_burned == expected_burn + second_burn

        # Annual tax is consensus state: exactly one year after Bob's first receipt,
        # the next valid block taxes Bob's full balance and resets his annual anchor.
        bob_anchor = bc.wallet_tax_anchor[bob.address]
        pre_annual = bc.balances[bob.address]
        treasury_before = bc.treasury_balance
        candidate = bc.build_candidate_block(miner.address)
        candidate.timestamp = bob_anchor + YEAR_SECONDS
        candidate.block_hash = ""
        candidate.mine()
        ok, reason, state = bc.validate_block(
            candidate, bc.chain[-1],
            (dict(bc.balances), dict(bc.nonces), bc.total_issued, bc.total_burned,
             bc.treasury_balance, dict(bc.miner_work), dict(bc.wallet_tax_anchor)),
            bc.chain, now=candidate.timestamp
        )
        assert ok, reason
        expected_annual_treasury = (pre_annual * RECEIVER_TAX_BPS) // 10_000
        expected_annual_burn = (pre_annual * TX_BURN_BPS) // 10_000
        expected_annual = expected_annual_treasury + expected_annual_burn
        assert state[0][bob.address] == pre_annual - expected_annual
        assert state[4] >= treasury_before + expected_annual_treasury
        assert state[6][bob.address] == bob_anchor + YEAR_SECONDS

        # A second block one second later cannot charge the same anniversary twice.
        later = dict(state[0])
        later_treasury, later_burned, later_anchors = Blockchain._apply_annual_wallet_taxes(
            later, state[6], state[4], bob_anchor + YEAR_SECONDS + 1
        )
        assert later_treasury == state[4]
        assert later_burned == 0
        assert later_anchors[bob.address] == bob_anchor + YEAR_SECONDS

        # Monthly Treasury distribution is proportional to verified PoW work.
        payout_balances = {"M1": 0, "M2": 0}
        payout_work = {"M1": 3, "M2": 1}
        remaining, work_after = Blockchain._distribute_treasury(payout_balances, 400, payout_work)
        assert remaining == 0
        assert work_after == {}
        assert payout_balances == {"M1": 300, "M2": 100}

        # No verified miner work: Treasury rolls over instead of disappearing.
        rollover_balances = {}
        remaining, work_after = Blockchain._distribute_treasury(rollover_balances, 400, {})
        assert remaining == 400
        assert work_after == {}

        # Verified PoW share test: challenge is tied to the current canonical tip.
        job_id = bc.chain[-1].block_hash
        share_difficulty = bc.share_difficulty(bc.chain[-1].difficulty)
        nonce = 0
        while True:
            share = make_mining_share(miner.address, job_id, share_difficulty, nonce)
            if share.is_valid(expected_job_id=job_id, expected_difficulty=share_difficulty):
                break
            nonce += 1
        assert bc.add_mining_share(share)
        candidate = bc.build_candidate_block(miner.address)
        assert any(r.get("type") == "mining_share" and r.get("share_id") == share.share_id for r in candidate.transactions)

        # Tamper test.
        tampered = [Block.from_dict(b.to_dict()) for b in bc.chain]
        tampered[1].transactions[-1]["amount"] = 999
        assert not bc.validate_chain(tampered)[0]

        # Persistence/replay test.
        bc2 = Blockchain(node_port=0, db_file=db)
        assert bc2.height == bc.height
        assert bc2.cumulative_work == bc.cumulative_work
        assert bc2.treasury_balance == bc.treasury_balance
        assert bc2.wallet_tax_anchor == bc.wallet_tax_anchor
        assert bc2.validate_chain(bc2.chain)[0]

    print("[SELF-TEST] all tests passed")


def run_node(args: argparse.Namespace) -> None:
    bc = Blockchain(
        node_port=args.port,
        db_file=args.db,
        initial_difficulty=args.difficulty,
    )

    node = P2PNode(
        bc,
        host=args.host,
        port=args.port,
        peers=args.peer,
        node_id=args.node_id,
    )
    node.start()

    miner_wallet = Wallet()
    print(f"[NODE] miner address: {miner_wallet.address}")

    if args.mine:
        print("[MINER] mining enabled")

        # Interrupt PoW quickly if a peer advances our tip.
        while True:
            stop_event = threading.Event()
            starting_tip = bc.chain[-1].block_hash

            def watch_tip() -> None:
                while not stop_event.is_set():
                    with bc.lock:
                        changed = bc.chain[-1].block_hash != starting_tip
                    if changed:
                        stop_event.set()
                        return
                    time.sleep(0.05)

            watcher = threading.Thread(target=watch_tip, daemon=True)
            watcher.start()

            try:
                block = bc.mine_pending(miner_wallet.address, stop_event=stop_event)
                if stop_event.is_set():
                    continue
                node.seen_blocks.add(block.block_hash)
                node.broadcast_block(block)
                print(
                    f"[MINER] block={block.index} "
                    f"difficulty={block.difficulty} "
                    f"work={bc.cumulative_work}"
                )
            except RuntimeError as e:
                if "interrupted" not in str(e):
                    print(f"[MINER] {e}")
            finally:
                stop_event.set()

            time.sleep(0.05)
    else:
        print(
            f"[NODE] height={bc.height} "
            f"work={bc.cumulative_work} "
            f"supply={bc.circulating_supply / COIN:.8f} EM"
        )
        try:
            while True:
                time.sleep(60)
        except KeyboardInterrupt:
            node.stop()


def main() -> None:
    parser = argparse.ArgumentParser(description="Electric Money v14 multi-node")
    parser.add_argument("--self-test", action="store_true")
    parser.add_argument("--host", default="0.0.0.0")
    parser.add_argument("--port", type=int, default=5000)
    parser.add_argument("--db", default=None)
    parser.add_argument("--difficulty", type=int, default=GENESIS_DIFFICULTY)
    parser.add_argument("--node-id", default=None)
    parser.add_argument(
        "--peer",
        action="append",
        default=[],
        help="peer as HOST:PORT; repeat for multiple peers",
    )
    parser.add_argument("--mine", action="store_true")
    args = parser.parse_args()

    if args.self_test:
        self_test()
        return

    run_node(args)


if __name__ == "__main__":
    main()
